<footer>
	<p>Sistema de control de gastos Version 1.0</p>
</footer>

<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
        <script>window.jQuery || document.write('<script src="<?php 
        echo APP_URL; ?> views/layouts/default/js/vendor/jquery-1.11.2.min.js"><\/script>')</script>
        <script src="<?php echo APP_URL; ?>
        views/layouts/default/js/vendor/bootstrap.min.js"></script>
        <script src="<?php echo APP_URL; ?>
        views/layouts/default/js/plugins.js"></script>
        <script src="<?php echo APP_URL; ?>
        views/layouts/default/js/main.js"></script>
        </body>
        </html>