<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>FRAMEWORK BÁSICO</title>
	<link rel="stylesheet" href="<?php echo APP_URL; ?>views/layouts/default/css/normalize.min.css">
	<link rel="stylesheet" href="<?php echo APP_URL; ?>views/layouts/default/css/bootstrap.min.css">
	<link rel="stylesheet" href="<?php echo APP_URL; ?>views/layouts/default/css/main.css">
  <link rel="stylesheet" href="<?php echo APP_URL; ?>views/layouts/default/css/style.css">
  <link rel="stylesheet" href="<?php echo APP_URL; ?>views/layouts/default/css/grid-responsive.css">
	<script src="<?php echo APP_URL; ?>views/layouts/default/js/vendor/modernizr-2.8.3.min.js"></script>
	</head>
	<body>
        <div class="container">
          <div class="row">
          <header>
          	<div class="col-md-6"><h1>Money Tracking</h1>
          	<div class="col-md-6">
		<h2>Hola<?php
		 echo $_SESSION['username'];?></h2>
		<a href="<?php echo APP_URL; ?>users/logout">Logout</a>
</div>
 </header>
</div>
<div class="row">
 <div class="col-ms-12">
  <nav>
  	<ul>
  		<li><a href="<?php echo APP_URL; ?>">Home</a></li>
  		<li><a href="<?php echo APP_URL; ?>pages">Pages</a></li>
  		<li><a href="<?php echo APP_URL; ?>users">Users</a></li>
  		<li><a href="<?php echo APP_URL; ?>categories">Categories</a></li>
  		<li><a href="<?php echo APP_URL; ?>transactions">Transactions</a></li>
  		<li><a href="<?php echo APP_URL; ?>accounts">Accounts</a></li>
  	</ul>
  </nav>
 	
 </div>
	
</div>